name: Python application

on:
  push:
    branches:
    - master
    - cognimaster

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install tutor-openedx
      run: |
        python -m pip install --upgrade pip
        pip install tutor-openedx
    - name: Build openedx image
      run: |
        docker login -u nunoferreira840 -p Joaon840#
        tutor config save --set DOCKER_IMAGE_OPENEDX=nunoferreira840/openedx-tutor:1.0
        tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=https://github.com/cognitiva/edx-platform.git 
        tutor images push openedx
        
        
    
